### ISSUE TITLE
Deintegrate for specific targets?

### ISSUE THREAD

**Issue by fatuhoku** [CocoaPods/cocoapods-deintegrate#18]
e.g. I want to deintegrate for specifically tests.

**Comment by segiddins** [comment]
This will happen automatically when using the CocoaPods 1.0 beta if you `pod install` after removing that target from your podfile.

**Comment by fatuhoku** [comment]
@segiddins ah! Awesome.

**Comment by chitaranjan** [comment]
@segiddins  hi 
Here is my pod file where i want to  uninstall some of the library   ...

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

pod 'Alamofire'
#pod 'Kingfisher', '~> 2.2'
#pod 'Onboard'
pod 'GoogleMaps'
pod 'Google/SignIn'
#pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
#pod 'RealmSwift'
pod 'PinterestSDK'
pod 'KMPlaceholderTextView', '~> 1.3.0'
pod 'GMImagePicker'
pod 'FBLikeLayout'
pod 'CollieGallery'
pod 'MXParallaxHeader'
pod 'SDWebImage'
pod 'PageMenu'
pod 'ObjectMapper'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'IQKeyboardManagerSwift', :git => 'https://github.com/hackiftekhar/IQKeyboardManager', :branch => 'swift3'
#pod 'SwiftWebViewBridge'
pod 'HTYTextField'
pod 'NVActivityIndicatorView'

target 'Homehapp' do
pod 'SwiftyJSON'
end

pod 'OAuthSwift', :git => 'https://github.com/OAuthSwift/OAuthSwift.git', :commit => '0b8f8d10e101d3c67c809fc2365c0ef07407ba47'

after removing this i used  pod install command   this error is showing ..


**[!] Unable to satisfy the following requirements:

- `SwiftyJSON` required by `Podfile`
- `SwiftyJSON (= 3.1.0)` required by `Podfile.lock`

None of your spec sources contain a spec satisfying the dependencies: `SwiftyJSON, SwiftyJSON (= 3.1.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.**

 this my  conf of my system

### Stack

```
   CocoaPods : 1.1.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 19263b022612fc934d42d8f7fe53e8b4c34fef70
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0



i am not able to uninstall the library please look at .
thanks
