### ISSUE TITLE
Unable to load plugin `cocoapods-deintegrate`

### ISSUE THREAD

**Issue by letvargo** [CocoaPods/cocoapods-deintegrate#22]
When testing my pod using travis, I get the following error message during the `pod lib lint` phase of the testing. The project actually builds fine, and the tests pass, but the warnings remain:

```
$ pod lib lint
[!] Unable to load a specification for the plugin `/Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-deintegrate-1.0.0.beta.1`
[!] Unable to load a specification for the plugin `/Users/travis/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-deintegrate-1.0.0.beta.1`
```

I'm not using `cocoapods-deintegrate` in my `Podspec` so I'm not sure where its coming from.

**Comment by segiddins** [comment]
What CocoaPods version are you running?

**Comment by letvargo** [comment]
`1.0.0.beta.8` - the latest and greatest!

**Comment by segiddins** [comment]
Can you try running `gem install claide --pre && pod --version && pod plugins installed --verbose` for me? Thanks!

**Comment by letvargo** [comment]
This is the output, but note that this was run on my macbook at home...the error that I'm getting occurs when I push to a github repo that then triggers the travis CI tests to begin. I don't get the error on my macbook. Part of me thinks I might have posted this in the wrong forum. It might not be a problem with the plugin at all - it might be a travis problem. Maybe commenting at travis-ci.org would be better...

```
$ sudo gem install claide --pre && pod --version && pod plugins installed --verbose
Password:
Successfully installed claide-1.0.0.beta.3
Parsing documentation for claide-1.0.0.beta.3
Done installing documentation for claide after 1 seconds
1 gem installed
1.0.0.beta.8

Installed CocoaPods Plugins:

cocoapods-deintegrate
    - Version:  1.0.0.beta.1
    - Homepage: https://github.com/kylef/cocoapods-deintegrate
    - Summary:  A CocoaPods plugin to remove and de-integrate CocoaPods from
    your project.

cocoapods-plugins
    - Version:  1.0.0.beta.1
    - Homepage: https://github.com/cocoapods/cocoapods-plugins
    - Summary:  CocoaPods plugin which shows info about available CocoaPods
    plugins.

cocoapods-search
    - Version:  1.0.0.beta.2
    - Homepage: https://github.com/CocoaPods/cocoapods-search
    - Summary:  Searches for pods, ignoring case, whose name matches `QUERY`. If
    the `--full` option is specified, this will also search in the summary and
    description of the pods.

cocoapods-stats
    - Version:  1.0.0.beta.4
    - Hooks:
      - post_install
    - Homepage: https://github.com/cocoapods/cocoapods-stats
    - Summary:  Uploads installation version data to stats.cocoapods.org to
    provide per-Pod analytics.

cocoapods-trunk
    - Version:  1.0.0.beta.4
    - Homepage: https://github.com/CocoaPods/cocoapods-trunk
    - Summary:  Interact with trunk.cocoapods.org

cocoapods-try
    - Version:  1.0.0.beta.4
    - Homepage: https://github.com/cocoapods/cocoapods-try
    - Summary:  CocoaPods plugin which allows to quickly try the demo project of
    a Pod.
```

**Comment by segiddins** [comment]
My guess is that on the machine that was experiencing the error, `pod` is actually loading a version < 1.0

**Comment by letvargo** [comment]
It might be loading a version of `cocoapods-deintegrate` < 1.0, but I'm pretty sure it is using the recent beta version of `pod`. I have this in my `.travis.yml` file:

```
before_install:
- gem install cocoapods -v 1.0.0.beta.8 # Since Travis is not always on latest version
- pod _1.0.0.beta.8_ install --project-directory=Tests
```

I'm explicitly installing the beta and then calling `pod` with the explicit version that I need...

I did it that way because I need to use the `install! ` command in my Podfile, so `0.39.0` wasn't working.

**Comment by segiddins** [comment]
Interesting, since the error message in the original issue is only in pre-1.0 versions of CLAide

**Comment by letvargo** [comment]
That command that you gave me - `gem install claide --pre && pod --version && pod plugins installed --verbose` - maybe I'll try adding it to my `.travis.yml` file and see what it tells me about the *other* machines plugins...

**Comment by letvargo** [comment]
You were right all along :)

I specified the version I wanted when I called `pod _1.0.0.beta.8_ install`, but I wasn't specifying the version of CocoaPods I wanted when `pod lib lint` was called. Changing it to `pod _1.0.0.beta.8_ lib lint` fixed all of the error messages. Thanks for your help.

**Comment by segiddins** [comment]
👍
