### ISSUE TITLE
Same class implemneted in two different pods

### ISSUE THREAD

**Issue by IronManAtYourService** [CocoaPods/cocoapods-deintegrate#29]
Get below error and app crashes, Like below error there are several other class defined which are implemented two different lib from salesforce. 
`Class DDTTYLoggerColorProfile is implemented in both /private/var/containers/Bundle/Application/9C8A5C92-A70F-4DA8-92B7-5E888F02DFA0/HughesNet Brasil.app/Frameworks/SalesforceKit.framework/SalesforceKit (0xd2a52c) and /private/var/containers/Bundle/Application/9C8A5C92-A70F-4DA8-92B7-5E888F02DFA0/HughesNet Brasil.app/Frameworks/CocoaLumberjack.framework/CocoaLumberjack (0x2d4188). One of the two will be used. Which one is undefined.`

**Comment by dnkoutso** [comment]
Is this even related? Going to close this I dont think its related to deintegration
