### ISSUE TITLE
"pod deintegrate" not running after "gem install cocoapods-deintegrate"

### ISSUE THREAD

**Issue by GreenRidingHood** [CocoaPods/cocoapods-deintegrate#32]
probably dum or silly something I am missing
first I run on terminal 
"sudo gem install cocoapods-deintegrate"
after that "pod deintegrate" , but I get error "pod: command not found" ..so

**Comment by amorde** [comment]
@GreenRidingHood apologies for the very late response - what version of CocoaPods do you have installed?

This plugin comes with CocoaPods by default, so you shouldn't have to install it manually.

Can you post the result of running `pod env` here?

**Comment by amorde** [comment]
going to close as this looks like CocoaPods itself is not installed. you can install it with `gem install cocoapods`

**Comment by JDerf** [comment]
Hey, I'm having this problem too.

When I run `pod env`  I get `command not found: pod`.

cocoapods-deintegrate (1.0.4) shows up in my gem list.

Any ideas?

**Comment by amorde** [comment]
does CocoaPods itself show up? ex `which pod`? if not, `gem install cocoapods` should do the trick
